# Generated by Django 5.2 on 2025-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('pH', models.FloatField()),
                ('nitrogen', models.IntegerField()),
                ('phosphorus', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('weather_info', models.CharField(max_length=200)),
                ('suitable_crops', models.CharField(max_length=200)),
            ],
        ),
    ]
