# Generated by Django 5.2 on 2025-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(choices=[('fertilizer', 'Fertilizer Store'), ('transport', 'Transport Agent'), ('expert', 'Expert Advisor')], default='fertilizer', max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
